### PR TITLE
Windows 32bit support

### PR DESCRIPTION
**Pull request by debjan**
```
Compiled with MSVC 14 under Python 3.3.5
```

### CODE REVIEW

**Comment by eerohele** [comment]
I don't have a Windows 32-bit machine to test this on, but I assume you've tested this on one and it works fine?

**Comment by debjan** [comment]
Yes, I tested it with [sublime-xpath](https://github.com/rosshadden/sublime-xpath)

**Comment by eerohele** [comment]
OK — Thanks!

**Comment by debjan** [comment]
Np. 
Should we ask for lxml `platforms` update at package control channel?

**Comment by eerohele** [comment]
Yeah, I can make the PR later today.

**Comment by debjan** [comment]
Nice

**Comment by eerohele** [comment]
https://github.com/wbond/package_control_channel/pull/5295

**Comment by eerohele** [comment]
@debjan: FYI: the PR was merged, so your contribution should now be available on Package Control.

**Comment by debjan** [comment]
Thanks

**Pull request merged**
